name: publish-to-nuget
on:
  release:
    types: [published, prereleased] # fires for both final releases and pre-releases

jobs:
  publish_sandbox:
    name: "🧪 Publish Package to NuGet Sandbox"
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == true || github.event.release.prerelease == false  # Sandbox runs for both pre-release and final release
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Fetch NuGet Asset from Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ github.event.release.tag_name }} --pattern "*.nupkg" --dir ./packages --repo ${{ github.repository }}

      - name: NuGet Sandbox Login
        uses: NuGet/login@v1
        id: login_sandbox
        with:
          user: CodersRealm
          token-service-url: https://nugettest.org
          audience: https://int.nugettest.org

      - name: Push to NuGet Sandbox
        run: |
          dotnet nuget push "./packages/*.nupkg" --api-key ${{ steps.login_sandbox.outputs.NUGET_API_KEY }} --source https://nugettest.org